### ISSUE TITLE
tii-sel4-vm not found

### ISSUE THREAD

**Issue by Jerryy959** [tiiuae/tii_sel4_manifest#1]
i'm running command "repo sync", but get the error

```
tii-sel4-vm:
remote: Repository not found
```

How can i fix it?

**Comment by hlyytine** [comment]
We realized our manifest contains repos (like tii-sel4-vm) that are available to TII internals only. Now the manifest is fixed so that everyone can checkout our sources. Right now the biggest changes are VM examples running on Raspberry Pi 4 and the build system running on Docker.

Check out the instructions at https://github.com/tiiuae/tii_sel4_build, note the section about checking out sources and `-m external.xml` options to `repo init`. I tested that at least you can build vm_minimal example on rpi4 without having TII account.

Please let us know if it works for you.

**Comment by Jerryy959** [comment]
Hi, @hlyytine 
Thanks very much for your help, I have successfully run `vm_minimal` 、 `vm_multi` and build the docker images, everything works well.
